# 책 설정
# 자세한 내용은 https://jupyterbook.org/customize/config.html 에서 확인하세요.

title: 데이터 과학을 위한 파이썬
author: Py4DS 커뮤니티
logo: logo.png
exclude_patterns: [_build, Thumbs.db, .DS_Store, "**.ipynb_checkpoints", ".venv", "README.md"]
# 각 빌드 시 노트북 강제 재실행.
# https://jupyterbook.org/content/execute.html 참조
execute:
  execute_notebooks: force
  timeout: 120
  exclude_patterns: ["README.md"]
  allow_errors: false
  nb_output_stderr: show


# PDF 빌드를 위한 라텍스 출력 파일 이름 정의
latex:
  latex_documents:
    targetname: book.tex

# 인용 생성을 위한 bibtex 파일 추가
bibtex_bibfiles:
  - references.bib

# 웹에 책이 있는 위치에 대한 정보
repository:
  url: https://github.com/aeturrell/python4DS  # 책의 온라인 위치
  branch: main  # 링크 생성 시 사용할 저장소 브랜치 (선택 사항)

# 책에 GitHub 버튼 추가
# https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository 참조
html:
  use_issues_button: true
  use_repository_button: true
  favicon: "favicon.ico"  # 파비콘 이미지 경로
  analytics:
    google_analytics_id: "G-LXJC37BJVX"  # 책 조회수 추적에 사용할 수 있는 GA ID

launch_buttons:
  colab_url: "https://colab.research.google.com"
  notebook_interface: "jupyterlab"  # 또는 "classic"
  binderhub_url: "https://mybinder.org"

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    bibtex_reference_style: author_year
    suppress_warnings: ["mystnb.unknown_mime_type"]
    nb_execution_show_tb: true
    nb_execution_raise_on_error: true  # 콘텐츠 오류 발생 시 빌드 실패 (오류가 있는 경우 게시하지 않음)
