project:
  type: book
  output-dir: _book

book:
  title: "Python4DS"
  author: "Arthur Turrell"
  date: "2/24/2026"
  language: ko
  chapters:
    - index.qmd
    - part: "서론"
      chapters:
        - introduction.ipynb
        - prerequisites.ipynb
    - part: "빠른 시작"
      chapters:
        - whole-game.ipynb
        - data-visualise.ipynb
        - workflow-basics.ipynb
        - data-transform.ipynb
        - workflow-style.ipynb
        - data-tidy.ipynb
        - workflow-writing-code.ipynb
        - data-import.ipynb
        - workflow-packages-and-environments.qmd
        - workflow-help.qmd
    - part: "시각화"
      chapters:
        - visualise.qmd
        - vis-layers.ipynb
        - exploratory-data-analysis.ipynb
        - communicate-plots.ipynb
    - part: "변형"
      chapters:
        - boolean-data.ipynb
        - numbers.ipynb
        - strings.ipynb
        - regex.ipynb
        - categorical-data.ipynb
        - dates-and-times.ipynb
        - missing-values.ipynb
        - joins.ipynb
    - part: "불러오기"
      chapters:
        - spreadsheets.ipynb
        - databases.ipynb
        - rectangling.ipynb
        - webscraping-and-apis.ipynb
    - part: "프로그래밍"
      chapters:
        - functions.ipynb
        - iteration.ipynb
        - command-line.qmd
    - part: "소통"
      chapters:
        - markdown.qmd
        - quarto.qmd

bibliography: references.bib

execute:
  enabled: true
  freeze: auto

format:
  html:
    theme: cosmo
    code-fold: true
    toc: true
    code-summary: "코드 보기"
