name: Release

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: "3.10"

      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          pixi-version: v0.39.1
          cache: true

      - name: Check if there is a parent commit
        id: check-parent-commit
        run: |
          echo "::set-output name=sha::$(git rev-parse --verify --quiet HEAD^)"

      - name: Detect and tag new version
        id: check-version
        if: steps.check-parent-commit.outputs.sha
        uses: salsify/action-detect-and-tag-new-version@v2.0.3
        with:
          version-command: |
            pixi run python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])"

      - name: Bump version for developmental release
        if: "! steps.check-version.outputs.tag"
        run: |
          pixi run bump-version &&
          version=$(pixi run python -c "import toml; print(toml.load('pyproject.toml')['project']['version'])") &&
          pixi run python -c "import toml; p=toml.load('pyproject.toml'); p['project']['version']='$version.dev.$(date +%s)'; toml.dump(p, open('pyproject.toml', 'w'))"
      
      - name: set timezone
        run: |
          TZ="Europe/London" &&
          sudo ln -snf /usr/share/zoneinfo/$TZ /etc/localtime

      - name: install linux deps
        run: |
          sudo apt-get -y install openssl graphviz nano texlive graphviz-dev unzip build-essential

      - name: Build book
        run: pixi run render --verbose

      - name: Publish
        if: steps.check-version.outputs.tag
        run: pixi run ghp-import

      - name: Publish the release notes
        uses: release-drafter/release-drafter@v6.0.0
        with:
          publish: ${{ steps.check-version.outputs.tag != '' }}
          tag: ${{ steps.check-version.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
